name = "drawdb-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
JWT_SECRET = "your-jwt-secret-key-change-this-in-production"
RESEND_API_KEY = "re_DCFgTEU7_N317DQ8p94gxBV3WtcoFoWi4"

[[d1_databases]]
binding = "DB"
database_name = "drawdb"
database_id = "ebcf83c9-4338-4d22-9ba8-af7c6657ece5"
migrations_dir = "migrations"
